# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js 18.x'

      - script: |
          cd AngularWithAzure/
          npm install -g @angular/cli
          npm install
          ng build --configuration production
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)'
      - task: CmdLine@2
        displayName: "Run unit tests"
        inputs:
          script: |
            cd AngularWithAzure/
            ng test --browsers=ChromeHeadless --code-coverage --watch=false
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/totemfrontend/'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: Development
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentDevelopment
    pool:
      vmImage: 'ubuntu-latest'
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:

            - task: AzureStaticWebApp@0
              inputs:
                app_location: '/'
                api_location: 'api'
                azure_static_web_apps_api_token: '3fc15732b04ca0cf2168343200a76dc8b2ad1157deb2819b9a600e8271de1b672-90613f22-7a71-4ba1-aa62-0ec4ca4a9e4b01e34850'
          
          
